Repository input-output-hk/mantis, pull requests merged in 2020-10, with the labels that each got.

#723 [ETCM-186] Fix strict pick with too few blocks
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherState.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
  src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherStateSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncSpec.scala
Labels: bug

#724 [ETCM-177] Fix Ommers pool
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
  src/main/scala/io/iohk/ethereum/consensus/ethash/EthashBlockCreator.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
  src/main/scala/io/iohk/ethereum/ommers/OmmersPool.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
  src/test/scala/io/iohk/ethereum/ommers/OmmersPoolSpec.scala
Labels: bug

#709 [ETCM-143] Redefine block header structure and encoding
  src/ets/scala/io/iohk/ethereum/ets/blockchain/Scenario.scala
  src/ets/scala/io/iohk/ethereum/ets/vm/ScenarioBuilder.scala
  src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainActor.scala
  src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainApp.scala
  src/it/scala/io/iohk/ethereum/txExecTest/util/FixtureProvider.scala
  src/main/scala/io/iohk/ethereum/blockchain/data/GenesisDataLoader.scala
  src/main/scala/io/iohk/ethereum/consensus/blocks/BlockGeneratorSkeleton.scala
  src/main/scala/io/iohk/ethereum/consensus/ethash/blocks/package.scala
  src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidator.scala
  src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSkeleton.scala
  src/main/scala/io/iohk/ethereum/consensus/validators/BlockWithCheckpointHeaderValidator.scala
  src/main/scala/io/iohk/ethereum/db/storage/BlockBodiesStorage.scala
  src/main/scala/io/iohk/ethereum/db/storage/BlockHeadersStorage.scala
  src/main/scala/io/iohk/ethereum/domain/Block.scala
  src/main/scala/io/iohk/ethereum/domain/BlockBody.scala
  src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
  src/main/scala/io/iohk/ethereum/extvm/VMServer.scala
  src/main/scala/io/iohk/ethereum/network/p2p/messages/CommonMessages.scala
  src/main/scala/io/iohk/ethereum/network/p2p/messages/PV62.scala
  src/main/scala/io/iohk/ethereum/rlp/RLPImplicits.scala
  src/main/scala/io/iohk/ethereum/utils/Picklers.scala
  src/test/scala/io/iohk/ethereum/Fixtures.scala
  src/test/scala/io/iohk/ethereum/ObjectGenerators.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncFixtures.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncSpec.scala
  src/test/scala/io/iohk/ethereum/checkpointing/CheckpointingTestHelpers.scala
  src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
  src/test/scala/io/iohk/ethereum/consensus/ethash/MinerSpecSetup.scala
  src/test/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSpec.scala
  src/test/scala/io/iohk/ethereum/consensus/validators/BlockValidatorSpec.scala
  src/test/scala/io/iohk/ethereum/consensus/validators/BlockWithCheckpointHeaderValidatorSpec.scala
  src/test/scala/io/iohk/ethereum/consensus/validators/OmmersValidatorSpec.scala
  src/test/scala/io/iohk/ethereum/domain/BlockHeaderSpec.scala
  src/test/scala/io/iohk/ethereum/domain/BlockchainSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/FilterManagerSpec.scala
  src/test/scala/io/iohk/ethereum/ledger/BlockRewardSpec.scala
  src/test/scala/io/iohk/ethereum/ledger/BlockValidationSpec.scala
  src/test/scala/io/iohk/ethereum/network/p2p/messages/NewBlockSpec.scala
Labels: BREAKS PROTOCOL, BREAKS STATE

#738 [ETCM-174] Sorting of checkpoint signatures
  src/main/scala/io/iohk/ethereum/consensus/blocks/CheckpointBlockGenerator.scala
  src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidator.scala
  src/main/scala/io/iohk/ethereum/consensus/validators/BlockWithCheckpointHeaderValidator.scala
  src/main/scala/io/iohk/ethereum/crypto/ECDSASignature.scala
  src/test/scala/io/iohk/ethereum/checkpointing/CheckpointingTestHelpers.scala
  src/test/scala/io/iohk/ethereum/consensus/validators/BlockWithCheckpointHeaderValidatorSpec.scala
Labels: BREAKS PROTOCOL

#749 [ETCM-211] Tracking of headers/bodies requests that will be ignored due to invalidation
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherState.scala
  src/test/scala/io/iohk/ethereum/BlockHelpers.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
Labels: bug

#729 [ETCM-76] network messages for checkpointing
  src/it/scala/io/iohk/ethereum/sync/util/CommonFakePeer.scala
  src/it/scala/io/iohk/ethereum/sync/util/RegularSyncItSpecUtils.scala
  src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainApp.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/BlockBroadcast.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/PeersClient.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/PivotBlockSelector.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/SyncController.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSync.scala
  src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
  src/main/scala/io/iohk/ethereum/network/EtcPeerManagerActor.scala
  src/main/scala/io/iohk/ethereum/network/handshaker/EtcHandshaker.scala
  src/main/scala/io/iohk/ethereum/network/handshaker/EtcNodeStatusExchangeState.scala
  src/main/scala/io/iohk/ethereum/network/p2p/MessageDecoders.scala
  src/main/scala/io/iohk/ethereum/network/p2p/messages/CommonMessages.scala
  src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
  src/test/scala/io/iohk/ethereum/Mocks.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/BlockBroadcastSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/PeersClientSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/PivotBlockSelectorSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/StateSyncSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncFixtures.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncSpec.scala
  src/test/scala/io/iohk/ethereum/db/storage/BlockBodiesStorageSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/DebugServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
  src/test/scala/io/iohk/ethereum/network/EtcPeerManagerSpec.scala
  src/test/scala/io/iohk/ethereum/network/PeerActorHandshakingSpec.scala
  src/test/scala/io/iohk/ethereum/network/PeerEventBusActorSpec.scala
  src/test/scala/io/iohk/ethereum/network/PeerManagerSpec.scala
  src/test/scala/io/iohk/ethereum/network/handshaker/EtcHandshakerSpec.scala
  src/test/scala/io/iohk/ethereum/network/p2p/PeerActorSpec.scala
  src/test/scala/io/iohk/ethereum/network/p2p/messages/MessagesSerializationSpec.scala
  src/test/scala/io/iohk/ethereum/network/p2p/messages/NewBlockSpec.scala
Labels: BREAKS PROTOCOL

#735 Etcm 175 sync reporting issues
  build.sbt
  src/it/scala/io/iohk/ethereum/sync/util/FastSyncItSpecUtils.scala
  src/it/scala/io/iohk/ethereum/sync/util/RegularSyncItSpecUtils.scala
  src/main/resources/application.conf
  src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/SyncController.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/SyncProtocol.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/SyncStateSchedulerActor.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSync.scala
  src/main/scala/io/iohk/ethereum/consensus/ethash/EthashMiner.scala
  src/main/scala/io/iohk/ethereum/consensus/ethash/MockedMiner.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
  src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
  src/main/scala/io/iohk/ethereum/nodebuilder/StdNode.scala
  src/main/scala/io/iohk/ethereum/utils/Config.scala
  src/test/scala/io/iohk/ethereum/BlockHelpers.scala
  src/test/scala/io/iohk/ethereum/ByteGenerators.scala
  src/test/scala/io/iohk/ethereum/Fixtures.scala
  src/test/scala/io/iohk/ethereum/SpecBase.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/EtcPeerManagerFake.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/FastSyncSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/StateSyncSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/TestSyncConfig.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/TestSyncPeers.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncFixtures.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncSpec.scala
  src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
  src/test/scala/io/iohk/ethereum/consensus/ethash/MinerSpecSetup.scala
  src/test/scala/io/iohk/ethereum/consensus/validators/BlockWithCheckpointHeaderValidatorSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerFixture.scala
  src/test/scala/io/iohk/ethereum/testing/ActorsTesting.scala
  src/test/scala/io/iohk/ethereum/utils/GenOps.scala
Labels: BREAKS STATE

#765 [FIX] Fix the way AsyncConfig is built
  src/main/scala/io/iohk/ethereum/utils/Config.scala
Labels: high priority

#760 [ETCM-247] Fix Fetcher updates
  src/it/scala/io/iohk/ethereum/sync/RegularSyncItSpec.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSync.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncSpec.scala
Labels: bug

#762 [Fix] Non checkpoint blocks after ECIP1097 should have HefPostEcip1097 extra fields
  src/main/resources/chains/etc-chain.conf
  src/main/resources/chains/eth-chain.conf
  src/main/resources/chains/mordor-chain.conf
  src/main/resources/chains/ropsten-chain.conf
  src/main/resources/chains/test-chain.conf
  src/main/resources/chains/testnet-internal-chain.conf
  src/main/scala/io/iohk/ethereum/consensus/blocks/BlockGeneratorSkeleton.scala
  src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
Labels: bug
