Repository input-output-hk/mantis, pull requests merged in 2020-12, with the labels that each got.

#826 [ETCM-205] Add information about checkpoints in tx history
  project/Dependencies.scala
  repo.nix
  src/main/scala/io/iohk/ethereum/domain/Address.scala
  src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/MantisJsonMethodImplicits.scala
  src/main/scala/io/iohk/ethereum/transactions/TransactionHistoryService.scala
  src/test/scala/io/iohk/ethereum/BlockHelpers.scala
  src/test/scala/io/iohk/ethereum/Mocks.scala
  src/test/scala/io/iohk/ethereum/ObjectGenerators.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/BlockBroadcastSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/PivotBlockSelectorSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/SyncSchedulerSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/TestSyncPeers.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncFixtures.scala
  src/test/scala/io/iohk/ethereum/cli/CliCommandsSpec.scala
  src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
  src/test/scala/io/iohk/ethereum/crypto/ECDSASignatureSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/MantisJRCSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/MantisServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServerSpec.scala
  src/test/scala/io/iohk/ethereum/network/EtcPeerManagerSpec.scala
  src/test/scala/io/iohk/ethereum/network/handshaker/EtcHandshakerSpec.scala
  src/test/scala/io/iohk/ethereum/network/p2p/MessageDecodersSpec.scala
  src/test/scala/io/iohk/ethereum/network/p2p/PeerActorSpec.scala
  src/test/scala/io/iohk/ethereum/network/p2p/messages/MessagesSerializationSpec.scala
  src/test/scala/io/iohk/ethereum/network/p2p/messages/ReceiptsSpec.scala
  src/test/scala/io/iohk/ethereum/transactions/TransactionHistoryServiceSpec.scala
Labels: wallet

#831 FIX: Update the bootstrap config
  src/main/resources/application.conf
  src/main/resources/chains/etc-chain.conf
  src/main/resources/chains/mordor-chain.conf
  src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
  src/main/scala/io/iohk/ethereum/network/discovery/PeerDiscoveryManager.scala
  src/test/scala/io/iohk/ethereum/network/discovery/PeerDiscoveryManagerSpec.scala
Labels: high priority

#829 [ETCM-396] faucet timeout
  src/main/scala/io/iohk/ethereum/faucet/FaucetConfig.scala
  src/main/scala/io/iohk/ethereum/faucet/SupervisorConfig.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetBuilder.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetRpcService.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/WalletRpcClient.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/client/RpcClient.scala
  src/test/resources/application.conf
  src/test/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetRpcServiceSpec.scala
  src/test/scala/io/iohk/ethereum/faucet/jsonrpc/WalletServiceSpec.scala
  src/universal/conf/faucet.conf
Labels: BREAKS CONFIG

#835 [FIX] Trigger block execution metrics on reorg as well
  src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
  src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
Labels: high priority

#840 [FIX] blacklist for longer in case of header validation failure
  src/main/resources/application.conf
  src/main/scala/io/iohk/ethereum/blockchain/sync/fast/FastSync.scala
  src/main/scala/io/iohk/ethereum/utils/Config.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/TestSyncConfig.scala
Labels: high priority

#847 Release 3.2.1
  build.sbt
  src/main/resources/chains/testnet-internal-nomad-chain.conf
  src/main/scala/io/iohk/ethereum/domain/Address.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
  src/universal/conf/testnet-internal-nomad.conf
Labels: release-candidate

#850 [ETCM-269] Add missing runToFuture to healthcheck endpoint
  src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServerSpec.scala
Labels: bug

#854 [ETCM-449] faucet duplicate config
  src/main/scala/io/iohk/ethereum/faucet/FaucetConfig.scala
  src/test/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetRpcServiceSpec.scala
  src/test/scala/io/iohk/ethereum/faucet/jsonrpc/WalletServiceSpec.scala
  src/universal/conf/faucet.conf
Labels: BREAKS CONFIG

#836 [ETCM-448] json rpc - status code
  src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServerSpec.scala
Labels: BREAKS API

#871 [ETCM-491] Extend generated bash script with absolute path configs
  build.sbt
  src/main/scala/io/iohk/ethereum/App.scala
  src/universal/bin/eckeygen.bat
  src/universal/bin/faucet-server.bat
  src/universal/bin/mantis-launcher
  src/universal/bin/mantis-launcher.bat
  src/universal/bin/mantis-vm.bat
  src/universal/bin/signatureValidator.bat
  src/universal/conf/application.ini
Labels: bug
