Repository input-output-hk/mantis, pull requests merged in 2020-11, with the labels that each got.

#757 [ETCM-185] Closing db
  src/main/scala/io/iohk/ethereum/db/dataSource/RocksDbDataSource.scala
  src/main/scala/io/iohk/ethereum/nodebuilder/StdNode.scala
Labels: bug

#772 [FIX] Return executed blocks sorted on execution error
  src/main/scala/io/iohk/ethereum/ledger/BlockExecution.scala
  src/test/scala/io/iohk/ethereum/BlockHelpers.scala
  src/test/scala/io/iohk/ethereum/ledger/BlockExecutionSpec.scala
  src/test/scala/io/iohk/ethereum/ledger/LedgerTestSetup.scala
Labels: bug

#780 [Chore] Fix nix dependencies
  repo.nix
Labels: high priority

#768 [ETCM-251] faucet healthcheck
  insomnia_workspace.json
  src/main/scala/io/iohk/ethereum/faucet/Faucet.scala
  src/main/scala/io/iohk/ethereum/faucet/FaucetApi.scala
  src/main/scala/io/iohk/ethereum/faucet/FaucetConfig.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetBuilder.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetDomain.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetJsonRpcController.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetJsonRpcHealthCheck.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetMethodsImplicits.scala
  src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetRpcService.scala
  src/main/scala/io/iohk/ethereum/faucet/package.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/serialization/JsonMethodDecoder.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/server/controllers/JsonRpcBaseController.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/server/http/BasicJsonRpcHttpServer.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpsServer.scala
  src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
  src/test/scala/io/iohk/ethereum/BlockHelpers.scala
  src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
  src/test/scala/io/iohk/ethereum/faucet/FaucetApiSpec.scala
  src/test/scala/io/iohk/ethereum/faucet/FaucetRpcServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/CheckpointingJRCSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerFixture.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/QaJRCSpec.scala
  src/test/scala/io/iohk/ethereum/ledger/BlockExecutionSpec.scala
  src/universal/conf/faucet.conf
Labels: BREAKS API

#763 [ETCM-178] Disallow duplicated connections and connections to self
  src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainActor.scala
  src/main/scala/io/iohk/ethereum/network/ConnectedPeers.scala
  src/main/scala/io/iohk/ethereum/network/Peer.scala
  src/main/scala/io/iohk/ethereum/network/PeerActor.scala
  src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
  src/main/scala/io/iohk/ethereum/network/discovery/PeerDiscoveryManager.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/DebugServiceSpec.scala
  src/test/scala/io/iohk/ethereum/network/EtcPeerManagerSpec.scala
  src/test/scala/io/iohk/ethereum/network/PeerEventBusActorSpec.scala
  src/test/scala/io/iohk/ethereum/network/PeerManagerSpec.scala
Labels: high priority

#790 [FIX] Return the last blocks when fetching the ommers ancestors from memory
  src/main/scala/io/iohk/ethereum/ledger/BlockValidation.scala
Labels: bug

#791 [ETCM-341] faucet - revert configs
  insomnia_workspace.json
  src/universal/conf/faucet.conf
Labels: bug

#792 [FIX] Fix UninstallFilter handling and make tests more reliable
  src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
  src/rpcTest/scala/io/iohk/ethereum/rpcTest/RpcApiTests.scala
Labels: bug

#800 [ETCM-377] Fix consistency issue between cache and persisted block number on rollbacks
  src/it/scala/io/iohk/ethereum/sync/util/CommonFakePeer.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
  src/main/scala/io/iohk/ethereum/db/storage/StateStorage.scala
  src/main/scala/io/iohk/ethereum/domain/Blockchain.scala
  src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
  src/test/scala/io/iohk/ethereum/db/storage/ReadOnlyNodeStorageSpec.scala
  src/test/scala/io/iohk/ethereum/domain/BlockchainSpec.scala
Labels: bug, high priority

#787 Etcm 290 invalid branches built by fetcher
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherState.scala
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
  src/main/scala/io/iohk/ethereum/domain/Block.scala
  src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherStateSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncSpec.scala
Labels: bug, high priority

#802 [Chore] Update nomad testnet configs
  src/main/resources/chains/testnet-internal-nomad-chain.conf
  src/main/resources/chains/testnet-internal-nomad-genesis.json
Labels: don't merge

#805 [FIX] Handle timeouts on BlockFetcher
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
Labels: bug

#808 [ETCM-135] Tx history improvements for wallet
  insomnia_workspace.json
  src/it/scala/io/iohk/ethereum/sync/util/CommonFakePeer.scala
  src/main/resources/application.conf
  src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/MantisJsonMethodImplicits.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/MantisService.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/TransactionResponse.scala
  src/main/scala/io/iohk/ethereum/jsonrpc/serialization/JsonEncoder.scala
  src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
  src/main/scala/io/iohk/ethereum/transactions/TransactionHistoryService.scala
  src/test/resources/application.conf
  src/test/scala/io/iohk/ethereum/blockchain/sync/StateSyncSpec.scala
  src/test/scala/io/iohk/ethereum/domain/BlockchainSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/CheckpointingJRCSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthTransactionSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerFixture.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/MantisJRCSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/MantisServiceSpec.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/QaJRCSpec.scala
  src/test/scala/io/iohk/ethereum/transactions/TransactionHistoryServiceSpec.scala
  src/test/scala/io/iohk/ethereum/transactions/testing/PendingTransactionsManagerAutoPilot.scala
  src/test/scala/io/iohk/ethereum/utils/VersionInfoSpec.scala
  src/universal/conf/testmode.conf
Labels: BREAKS API, BREAKS CONFIG, high priority, wallet

#813 [FIX] Fix NPE thrown during cake building
  src/main/scala/io/iohk/ethereum/consensus/ConsensusBuilder.scala
  src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
  src/test/scala/io/iohk/ethereum/jsonrpc/MantisServiceSpec.scala
Labels: bug, high priority

#814 [ETCM-415] Fix random subset of peers where block is broadcasted
  src/main/resources/application.conf
  src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockBroadcast.scala
  src/main/scala/io/iohk/ethereum/utils/Config.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/BlockBroadcastSpec.scala
  src/test/scala/io/iohk/ethereum/blockchain/sync/TestSyncConfig.scala
Labels: bug

#820 [ETCM-426] Changed the gas limit strategy to a constant one
  src/main/resources/chains/testnet-internal-gac-genesis.json
  src/main/resources/chains/testnet-internal-nomad-genesis.json
  src/main/scala/io/iohk/ethereum/consensus/blocks/BlockGeneratorSkeleton.scala
  src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
Labels: BREAKS STATE

#815 Add miners whitelist to testnet configs
  src/main/resources/chains/testnet-allowed-miners.json
  src/main/resources/chains/testnet-internal-gac-chain.conf
  src/main/resources/chains/testnet-internal-nomad-chain.conf
  src/universal/conf/base-testnet.conf
Labels: BREAKS PROTOCOL
